# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_studentsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='subject',
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
    ]
